### ISSUE TITLE
Unsafe release workflow

### ISSUE THREAD

**Issue by bboilot-ledger** [aido/app-seed-tool#37]
**Describe the bug**
The release workflow is triggered by a "workflow_run" event. So anyone doing a pull request can trigger this workflow. The only restriction is that the branch starts with a "v" letter which is easy because the branch name is controlled by the contributor.
So any contributor could create a release containing is changes.

**Expected behavior**
Contributors should not be able to generate releases or control workflows with privileges (write access to repo).

**Possible fix**
One way could be to ensure that this workflow only run from a branch and cannot be triggered by a PR.
Another way could be to trigger this workflow on tag push.

**Comment by aido** [comment]
Hi @bboilot-ledger,

Good point!
I have updated the conditions for when a release workflow is triggered. It will now only trigger for pushes to the 'develop' branch.

**Comment by aido** [comment]
Hi again @bboilot-ledger, 

This was bugging me so I looked at it again.

The `Create Release` workflow is triggered on completion of the `Compilation & tests` workflow:
```yml
name: Create Release

on:
  workflow_run:
    workflows: ['Compilation & tests']
    types:
      - completed
```

The `Compilation & tests` workflow only triggers on pushes to the develop branch:
```yml
name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
```

So I don't think `Create Release` was actually an unsafe workflow. I will leave the recent update in place nonetheless.
